# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0002_auto_20181003_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(blank=True, to='instagramapp.tags'),
        ),
    ]
