# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0003_auto_20181003_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=140)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
