# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-07 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0005_auto_20181005_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instagramapp.Image'),
        ),
    ]
