# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-07 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0006_review_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
