# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 09:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instagramapp', '0013_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='value',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set([('user', 'image', 'value')]),
        ),
    ]
